services:
  - type: web
    name: coursecraft
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: coursecraft-c31f9
      - key: SMTP_USER
        value: kadamsweta92@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_SECURE
        value: "true"
      - key: RESEND_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dinrv92oo
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false


